### PR TITLE
Update supported python versions

### PR DESCRIPTION
**Pull request by altheaden**
`conda-forge` has recently dropped support for python 3.8 and gained support for python 3.12, so I am updated these versions in this PR.

### CODE REVIEW

**Comment by altheaden** [comment]
I haven't done any testing yet, but I can if desired. I am not sure if it's needed for these changes. I added a file in the `ci` folder for 3.12, but it's just based on the prior files (3.9 to 3.11), so it might not be set up correctly. I see that CI is failing for 3.12 so maybe there's something else I need to add to this, but I'm not sure what.

**Comment by xylar** [comment]
@altheaden and I discussed that we will first try to update the GitHub Actions workflow to no longer use mamba/mambaforge and see if that fixes python 3.12.

**Comment by xylar** [comment]
@altheaden, can you rebase this one now that I merged #65?

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
@altheaden, I think something is still wrong with the workflow here.  This step:
https://github.com/MPAS-Dev/pyremap/blob/eab1c1165beb80996b143f480499e05544466f59/.github/workflows/build_workflow.yml#L91-L95
should use `conda create` like we do on mache:
https://github.com/E3SM-Project/mache/blob/main/.github/workflows/build_workflow.yml#L96-L102
Could you see if you can make that change?  I think using `conda install` is not behaving well.

**Comment by xylar** [comment]
@altheaden, I think we might be able to fix the current issues by removing these lines:
```
          # IMPORTANT: This needs to be set for caching to work properly!
          use-only-tar-bz2: true
```
Despite the comment, this is no longer needed.

**Comment by altheaden** [comment]
@xylar I assume you have already looked at the changes I made in the build workflow (to match mache's, minus the `-e` in the pip command). You were right about the "important" line (haha). I think everything should be working now.

**Review by xylar — APPROVED** [review]
Okay, great!  I think we're finally in business.

**Comment by xylar** [comment]
> @xylar I assume you have already looked at the changes I made in the build workflow (to match mache's, minus the -e in the pip command). You were right about the "important" line (haha). I think everything should be working now.

Yes, as I think we discussed, the `-e` doesn't make sense in CI (thought it does no harm).  So this looks great!

**Comment by xylar** [comment]
Thanks for the hard work on this @altheaden!

**Pull request merged**
